//
//  HomePresenter.swift
//  TestExample
//
//  Created by Hélio Mesquita on 11/10/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol HomePresentationLogic {
    func showInvalidData()
    func weightBelowBormal()
    func normalWeight()
    func overweight()
    func obesityI()
    func obesityII()
    func obesityIII()
}

class HomePresenter: HomePresentationLogic {
    
    weak var viewController: HomeDisplayLogic?

    func showInvalidData() {
        viewController?.showResult(text: "The inserted data is invalid")
    }

    func weightBelowBormal() {
        viewController?.showResult(text: "You are under weight")
    }

    func normalWeight() {
        viewController?.showResult(text: "You are normal weight")
    }

    func overweight() {
        viewController?.showResult(text: "You are overweight")
    }

    func obesityI() {
        viewController?.showResult(text: "You are Obesity I")
    }

    func obesityII() {
        viewController?.showResult(text: "You are Obesity II")
    }

    func obesityIII() {
        viewController?.showResult(text: "You are Obesity III")
    }

}
